### ISSUE TITLE
New module idea: parachutes. see comments.

### ISSUE THREAD

**Issue by togfoxy** [togfoxy/MarsLander#141]
I'm thinking a module to purchase is a parachute. It is a one use item (and priced accordingly) that auto-deploys when you run out of fuel. It lets the lander drift gently to the surface without too much damage. I'm thinking you can use the side thrusters to gently steer to a fuel base. It's like a last gasp 2nd chance thing.

If you have parachutes and side thrusters then the thrusters use free fuel just for this scenario.

If you have a parachute and no side thruster then best of luck. You might still randomly land on a fuel tank (but probably not).

**Comment by Philbywhizz** [comment]
That's a good idea for a module.You could even have an element of wind speed and direction as a variable.

**Comment by MadByteDE** [comment]
Sounds good to me.

**Comment by togfoxy** [comment]
Not related to screen res or mplayer so will drop from this release.
