### ISSUE TITLE
ResetGame doesn't reset the Lander.Health

### ISSUE THREAD

**Issue by togfoxy** [togfoxy/MarsLander#146]

**Comment by togfoxy** [comment]
So checking the code this shouldn't be a thing. Maybe I imagined it. I'll leave this here for now.

**Comment by MadByteDE** [comment]
Cant confirm this. I tested resetting after fuel is empty and via new game button.

**Comment by Philbywhizz** [comment]
I also can't seem to recreate this issue.

**Comment by togfoxy** [comment]
I'll put this down to my buggy branch and close this ticket. Thanks.
