### ISSUE TITLE
Code style guide

### ISSUE THREAD

**Issue by MadByteDE** [togfoxy/MarsLander#154]
Since I'm neck-deep into restructuring the game's code, I can't help but notice how different code is written in general - even inside a single file. As of now I tried to avoid changing the style of the functions in a major way, but I have to admit, every time I come across one such function, I'm tempted to change the format to what I'm used to :smile_cat: 

So, I wonder if it would be possible to get everyone onto the same page regarding the style of the project's code base. 
I'm sure everyone has their own preferences when it comes to the coding style - I'm also doing quite some stuff that isn't written in any of the style guides out there since I'm used to it - but that doesn't mean that my way works great for a community project with many contributors. 

There are numerous different style guides available for lua code, but some are more commonly used then others. One I particularly like is [flamendless' style guide](https://flamendless.github.io/lua-coding-style-guide/) which conveniently features some LÖVE-specific tweaks since it's written by a fellow löver. 

One major change for me in particular that comes up in most style guides out there  is using snake_case_function_names, but I can see why it is practiced that way. 

So as a general question, would you guys be open to follow one of the many styles guides out there - or is this something you'd like to not touch and continue going wild west with the code? :cowboy_hat_face: 

(or even work out our own guide?)

### Links to some more guides
[Lua-users.org](http://lua-users.org/wiki/LuaStyleGuide)
[Coregamers](https://docs.coregames.com/tutorials/lua_style_guide/)
[luarocks](https://github.com/luarocks/lua-style-guide)

**Comment by togfoxy** [comment]
I'm happy to describe my style (the original code base) or adopt another.

My only request (not a demand) is that underscores are avoided. I know 99% of coders use them but they are hard for touch-typists to use, inefficient (two keystrokes vs one or none) and frankly hard to read.

I like to prepend globals with a 'g'.

I prepend with types to help readability and maintenance. I don't do this for locals but probably should.

If functions return a value then I describe the type that is returned. Saves me teasing comments or unpacking a function that is not written.

There is much more in a style guide but that's what the original pattern was.

All of that is negotiable.

**Comment by togfoxy** [comment]
After reading that Flame guide I think I can do all those things but CamelCase matches my workflow best

**Comment by MadByteDE** [comment]
> My only request (not a demand) is that underscores are avoided. I know 99% of coders use them but they are hard for > touch-typists to use, inefficient (two keystrokes vs one or none) and frankly hard to read.

I'm with you here. As I mentioned, snake_case_stuff is also not very intuitive to type for me.
But I'd also like to avoid PascalCase for function names and variables and use camelCase for them:

![PascalCase vs camelCase](https://i.imgur.com/4Qw0Iov.png)

Since this the the way love functions are made and I'd find it counter-intuitive to use camelCase for love functions but PascalCase for our own functions.

PascalCase is more suitable for classes and modules (including libraries) imo.

> I like to prepend globals with a 'g'.

Usually I just avoid globals, and If I really need one, I do the ALL_UPPERCASE thing.
One trick to avoid globals might be to put stuff like screenWidth, screenHeight and other globally needed things into a module and access them that way locally for each file:

`
local var = require("var")

player.x = var.screenWidth/2
player.y = var.screenHeight/2
`

A bit like the enum.lua we got already.


> I prepend with types to help readability and maintenance. I don't do this for locals but probably should.

I get the intention, personally I think that reduces readability a bit. Since globals should be avoided anyway, the g could be obsolete. Regarding int, str etc. I think that it can be helpful, but not if it's not used consistently for everything - and even then I prefer shorter variable names since most of the time it should be obvious what type a var is, and if not - most IDEs / code editors I used show the type when hovering over the var:

![VSCode](https://i.imgur.com/BQRefLE.png)

> If functions return a value then I describe the type that is returned. Saves me reading comments or unpacking a function that is not written with comments.

I'm not sure what you mean by that, can you give an example?

> All of that is negotiable.

Same.

**Comment by togfoxy** [comment]
I'm fine with camelCase.

I'm fine with the way you want to do globals.  If we must use globals then full UPPERCASE is also fine.

(More comments to come ...)

**Comment by Philbywhizz** [comment]
This is a great topic. A coding style is important! We have gotten away with it so far since it really has only been 2 of us to begin with. That's probably what the 2 clashing styles are. Now there are 3 of us (and potentially more coming as we grow) and if we want more people to contribute and get involved in the code then its best to come up with at least a guide, and more importantly stick to it.

As for myself, I really don't have a particular preference to be honest. camelCase, PascalCase, annoying_underscore_names, I've used them all in some shape or form in other languages or scripts. UPPERCASE for globals seems to be the popular choice.

I switch between use Visual Studio Code and vim (depending on my mood) but I don't really use much of the IDE settings and helpers (except for colors). IDE's are a personal preference anyway.

I'm so used to following different style guides for different clients during my work day that my style is a bit of a mix mash when it comes to my personal projects. If a style is defined then I'll follow it, because that's what I am used to (and have to do) for work. :)

I'm not a very strong coder in lua (it's why I'm here - to learn and practice it), so I don't think I'm in the best position to define what the style should be.

**Comment by MadByteDE** [comment]
> function IsLanderDead() could return true or false or 0 or 1 or 1 or 2 depending on personal style, preferences and experience with different languages.
>
>function bolIsLanderDead() has no ambiguity at all.

Right, but in that case I think we could just agree to return true or false - 0 or 1 wouldn't make any sense because we'd need to convert the boolean we get from e.g if-statement into a number which sounds silly :grin:  . Personally I never had to code something that required me to differentiate between 3 or more return codes like 0=ok, 1=unknown_fail, 2=wrong_type or something like that. 
Do you think we'd need this in future?

> function DecreaseFuel(lander,10) will operate directly on 'lander' and is a procedure.
>
> function objDecreaseFuel(lander,10) will return something a function).

Sorry, I don't get what the objDecreaseFuel function is supposed to do in your example. The naming scheme for this doesn't look usable anyway since obj should be the object itself like `Lander.decreaseFuel` . Maybe I misunderstood what you said.

> I'm not a very strong coder in lua (it's why I'm here - to learn and practice it), so I don't think I'm in the best position to define what the style should be.

I believe non of us really is :smile:  

I get the argument that @togfoxy prepend variables with their type because ZeroBrane or Notepad++ don't support more advanced features like Atom or VSCode. But I'm not sure what we can do about it. So we may have to keep them. I just think they are not that great for readability overall, especially combined with the other common formatting schemes.  
```
INTSCREENWIDTH = 1024 -- very bad
INT_SCREENWIDTH = 1024 -- a bit better
SCREEN_WIDTH = 1024 -- would be my favorite (SNAKE_CASE just for global and constant variables for readability)
INT_SCREEN_WIDTH = 1024 -- combined with a prefix, looks ok I guess but is pretty long
```
I think for values that aren't used that often like assets, long variable names shouldn't be a problem. But something like screenWidth is used pretty often. It would be much easier to just do the following in that case:
```
local screenWidth, screenHeight = love.graphics.getDimensions()

function bla()
    player.x = screenWidth/2
end
```

**Comment by togfoxy** [comment]
I just realised by example doesn't make sense with the new file format. You are absolutely right that Lander.decreasefuel is the future and makes my previous comments redundant.  :)  Hence your (our) confusion. Lets see if we have landed on some things:

- we prefer camelCase
- avoid globals but use UPPERCASE when they can't be avoided
- no prepending with g or data types
- boolean functions return true or false and not numbers

How close is all that to the original flamendness style guide?

**Comment by MadByteDE** [comment]
> How close is all that to the original flamendness style guide?

Pretty close. Only difference is the snake_case with normal local variables and functions. But I believe we consent that we use `function Lander.isOnLandingPad()` instead of `function Lander.is_on_landing_pad()`.

What are we going to do with "constants" and function names? 

For constants, the coregames guide uses ALL_UPPERCASE because no globals seem to be allowed, at all. We could do the same, but that would make things quite a lot harder. Or we do what coregames does with enum entries - `Module.COST_THRUSTERS = 225`.

Regarding function names. For me it doesn't matter really if we use PascalCase or camelCase. What do both of you prefer?

**Comment by Philbywhizz** [comment]
For functions names, I'd prefer camelCase given the choice.

**Comment by togfoxy** [comment]
I don't mind but we have agreed on camel case elsewhere so let's be consistent.

**Comment by Philbywhizz** [comment]
I've added an entry to the [wiki](https://github.com/togfoxy/MarsLander/wiki/3.-Coding-Style-Guide) that give a summary of what we have discussed above. Feel free to update it if needed. 
I've tried to keep it simple.

**Comment by togfoxy** [comment]
Do we want to link to that flamed thingy style guide and call out exceptions? Is that an easier approach?

**Comment by Philbywhizz** [comment]
Now that we have a wiki up with a style guide, I think we can safely close this issue off.
