### ISSUE TITLE
Need to round off netcode values so they don't have lots of decimal places

### ISSUE THREAD

**Issue by togfoxy** [togfoxy/MarsLander#157]

**Comment by MadByteDE** [comment]
I'd add this to v0.11 since this could potentiality cause such things as delay and lag easily. The less data, the absolute better.

**Comment by togfoxy** [comment]
The new enet code should fix this but I'll review it after v0.11.  It won't impact single player mode.

**Comment by togfoxy** [comment]
New enet code resolves this.
