### ISSUE TITLE
Big performance drop every couple seconds

### ISSUE THREAD

**Issue by MadByteDE** [togfoxy/MarsLander#160]
I'm sure you also noticed the slowdown that happens every couple seconds.
The cause is that our code produces a lot of garbage (memory) that get's collected from time to time. 

Here is small video showing the performance drop when the garbage get's collected

https://user-images.githubusercontent.com/4752038/140398076-192faad7-c2dc-4327-9ab0-5d00b2eb304b.mp4

To solve the issue we need to optimize the mem usage significantly. The terrain  generation might be one of the bigger contributors to that issue.

**Comment by togfoxy** [comment]
I don't notice on windows but I have no doubt you are right.

**Comment by MadByteDE** [comment]
Okay, I've identified the issue. The code responsible for pre-generating the positions for all the refuel bases fills the garrGround table with a painful lot of entries with the line `if basedistance > #garrGround then Terrain.getNoise(basedistance * 2) end`.

We need a way to predefine positions for bases and buildings **without** generating all the terrain for it.
Also we need to generate, update and draw just the terrain, buildings etc that is/are directly near the player. Everything else shouldn't be present at runtime. 

Maybe we could keep **small** tables just saving the x position for objects and if the player is near that position, the object will actually be created. And if the player get a set distance away then the object will be destroyed and e.g for refuel bases, just an entry with it's id and the fuelCapacity will be saved just in case the player comes back and tries to refuel again.

y position can be generated on-the-fly to make sure the object sit's on the surface.

> I don't notice on windows but I have no doubt you are right.

Thanks for your trust :heart_eyes: 

I assume you just woke up & I'm about to go to bed? hehe. 
Have a nice day :wink:

**Comment by togfoxy** [comment]
Functionality and just getting the darn thing to work was the focus. Optimizing was always going to be needed.

Like the way I just optimised the socket code. Iterative improvements.

Glad you found that one about the bases.

Good night!

**Comment by MadByteDE** [comment]
> Functionality and just getting the darn thing to work was the focus. Optimizing was always going to be needed.

Sure, no worries :wink:
