### ISSUE TITLE
File duplicates added with recent commits (togfoxy)

### ISSUE THREAD

**Issue by MadByteDE** [togfoxy/MarsLander#161]
@togfoxy's following commits:
4830126bae45cfd8dd1e673b3f82834afe6d0729
46074ed2826576e21f07b1b7344b0235987dd97d

added new files to the base directory of the repository instead of changing existing files in the source directory.

The source directory seems to be present since the initial commit to the repo and was used for all recent changes:
5c3d985e158f8296d15f8ad21f47d989de655820

To avoid further confusion maybe we should get rid of the source directory and instead manage all game files from the root directory (same dir as CHANGELOG.md to be clear).

Since there is a PR pending, that still relies on the source directory, I'd say we should review the PR first and when it's closed we can go ahead and merge the files from the root directory with the files in the source directory - otherwise I'd worry that I'd need to re-base my working branch and all the changes will be gone.

To be save, I created a local back-up of my working branch, so If you guys want to try something out to resolve this first, go ahead.

**Comment by togfoxy** [comment]
The source is what goes into the.love file.  Everything else (manuals, screenshots, videos, promotional materials, sound tracks) goes outside of source.

As this is a community project I'd like  all materials to be available to all on github - Including material that doesn't go into the .love file.

**Comment by MadByteDE** [comment]
> As this is a community project I'd like all materials to be available to all on github - Including material that doesn't go into the .love file.

That's fine of course, but we really shouldn't have duplicates of the source files in the root directory of the repo imo. This is just confusing & may lead to bugs because someone pushes changes to the wrong file. 

Just out of curiosity - what do you need the .lua files in the root directory for? couldn't you put your persoanl, copied source files into another local directory that is not within the scope of the repo?

I feel like we kinda talk past each other. :yum:

**Comment by togfoxy** [comment]
I miss understood.

.lua files should NOT be in root. They should be in source.

Did I add them to root by mistake?

**Comment by togfoxy** [comment]
I think Phil cleaned up a previous instance where this happened. I'll need to check how that happened. I use two different computers in different locations so I'll double check what's going on.

**Comment by togfoxy** [comment]
Fixed. That was all my bad. Closing ticket.
