### ISSUE TITLE
Bug when landing on fuel base with no fuel. See comments.

### ISSUE THREAD

**Issue by togfoxy** [togfoxy/MarsLander#171]
The 'reset game' message comes up when run out of fuel but if you land on a fuel base with no fuel (which triggers a refuel) then the 'reset game' doesn't clear.

**Comment by MadByteDE** [comment]
070571c8a310b760d4619b378c9ad45abeac5983
ace7b40dc992e3dd96a6a8cfdccaedd93f674735
fixed.
