### ISSUE TITLE
The SAVE game (and probably LOAD game) is broken

### ISSUE THREAD

**Issue by togfoxy** [togfoxy/MarsLander#173]

**Comment by MadByteDE** [comment]
Can you elaborate on that? Is this caused by the changes to terrain generation or something I changed?
Did this work previously? Asking because it seems to be caused by userdata which shouldn't be serialized anyway.

**Comment by togfoxy** [comment]
It use to work.

I think a sprite/image has snuck into a table and that can't be serialised.

**Comment by togfoxy** [comment]
lander.sprite = garrImages[5]

Storing a sprite in the table makes the table difficult to serialise.

**Comment by MadByteDE** [comment]
Oh my bad, maybe because I didn't think of the save feature like at all. Doesn't make sense to store the image in the lander.table.
