### ISSUE TITLE
Update the player wiki

### ISSUE THREAD

**Issue by togfoxy** [togfoxy/MarsLander#224]
There will be multiplayer functions, new settings and the P & O key should be described.

**Comment by Philbywhizz** [comment]
I've made a start on this already [here](https://github.com/togfoxy/MarsLander/wiki/1.-Player-Guide). Needs more work, but that's what wiki's are for, incremental changes. :)

**Comment by togfoxy** [comment]
I've added to it myself so now it is current for the intended v0.11. Thx!
