### ISSUE TITLE
Need to create a wiki

### ISSUE THREAD

**Issue by togfoxy** [togfoxy/MarsLander#93]

**Comment by Philbywhizz** [comment]
I might start setting this up given we are starting to create and discus things (such as Coding styles, etc)

**Comment by togfoxy** [comment]
I was thinking the wiki is for game players - like a user manual/instructions. Can we do one for coders as well? Does it work that?

**Comment by Philbywhizz** [comment]
We can have a page or players, and a page for coders. It's a wiki - so anyone can change/update it.
I can't see it getting to big and complicated (I could be wrong). It's probably more important to get 'something' up there and see what works and what doesn't. If it doesn't work then we can try something else. :)

**Comment by togfoxy** [comment]
Players will want to know about modules and what they do. Controls. bases. Health. Score If I ever get mplayer to work then that will need explaining.  Lots of things to explain in good time. Lets build it piece by piece.  :)

**Comment by Philbywhizz** [comment]
"Build it and they will come"
